FORBIDDEN_TYPES = {
    "Thing",
    "Entity",
    "Item",
    "Location",
}

GENERIC_TYPES = {
    "Unknown",
    "Place",
    "Organization",
    "Service",
    "Concept",
    "Accommodation",
}

GENERIC_RESCUE_CANDIDATES = {
    "Unknown",
    "Place",
    "Concept",
    "Organization",
    "Service",
    "Accommodation",
}

CANONICAL_TYPE_MAP = {
    "hotel": "Hotel",
    "hotels": "Hotel",
    "hostel": "Hostel",
    "hostels": "Hostel",
    "albergue": "Hostel",
    "albergues": "Hostel",
    "lodging": "Accommodation",
    "accommodation": "Accommodation",
    "restaurant": "Restaurant",
    "restaurants": "Restaurant",
    "foodestablishment": "FoodEstablishment",
    "museum": "Museum",
    "museums": "Museum",
    "airport": "Airport",
    "airports": "Airport",
    "bar": "Bar",
    "bars": "Bar",
    "cafe": "Cafe",
    "cafes": "Cafe",
    "coffee shop": "Cafe",
    "tourist attraction": "TouristAttraction",
    "touristattraction": "TouristAttraction",
    "attraction": "TouristAttraction",
    "historicalorculturalresource": "HistoricalOrCulturalResource",
    "archeologicalsite": "ArcheologicalSite",
    "archaeologicalsite": "ArcheologicalSite",
    "eventorganisationcompany": "EventOrganisationCompany",
    "townhall": "TownHall",
    "exhibitionhall": "ExhibitionHall",
    "park": "Park",
    "garden": "Garden",
    "bridge": "Bridge",
    "church": "Church",
    "monastery": "Monastery",
    "palace": "Palace",
    "market": "Market",
    "theatre": "Theatre",
    "theater": "Theatre",
    "arena": "Arena",
    "sportsvenue": "SportsVenue",
    "fortification": "Fortification",
    "gate": "Gate",
    "street": "Street",
    "route": "Route",
    "excursion": "Excursion",
    "activity": "Activity",
    "guidedtour": "GuidedTour",
    "tourismservice": "TourismService",
    "dish": "Dish",
    "dessert": "Dessert",
    "drink": "Drink",
    "foodproduct": "FoodProduct",
    "contentpage": "ContentPage",
    "categorypage": "CategoryPage",
}

TYPE_PRIORITY = {
    "Hotel": 100,
    "Hostel": 100,
    "Accommodation": 80,
    "Restaurant": 100,
    "FoodEstablishment": 90,
    "Cafe": 90,
    "Bar": 90,
    "Museum": 100,
    "Airport": 100,
    "TouristAttraction": 95,
    "Monument": 92,
    "Castle": 95,
    "Basilica": 95,
    "Cathedral": 95,
    "Church": 95,
    "Chapel": 90,
    "Monastery": 94,
    "Palace": 94,
    "Square": 88,
    "TownHall": 92,
    "Park": 92,
    "Garden": 90,
    "Bridge": 94,
    "Street": 82,
    "Market": 88,
    "Theatre": 92,
    "Arena": 92,
    "SportsVenue": 92,
    "Fortification": 92,
    "Gate": 88,
    "ArcheologicalSite": 90,
    "HistoricalOrCulturalResource": 70,
    "Event": 92,
    "ExhibitionHall": 88,
    "Activity": 82,
    "Route": 84,
    "Excursion": 88,
    "GuidedTour": 86,
    "TourismService": 82,
    "EventOrganisationCompany": 60,
    "Dish": 90,
    "Dessert": 90,
    "Drink": 88,
    "FoodProduct": 88,
    "ContentPage": 5,
    "CategoryPage": 5,
    "Organization": 10,
    "Service": 20,
    "Place": 5,
    "Concept": 0,
    "Unknown": 0,
}

PAGE_TYPE_PATTERNS = {
    "place_detail": [
        "/lugar/",
        "/en/lugar/",
    ],
    "event_detail": [
        "/evento/",
        "/evento/",
        "/en/evento/",
    ],
    "listing_page": [
        "/lugares/page/",
        "/en/lugares/page/",
    ],
    "category_page": [
        "/tipo-lugar/",
        "/category/",
        "/en/lugares",
        "/lugares",
    ],
    "blog_page": [
        "/blog",
    ],
    "professional_page": [
        "/profesional",
        "/eventos-del-sector",
    ],
}

BAD_NAME_TOKENS = {
    "categorías",
    "categorias",
    "todos los lugares",
    "planifica tu viaje",
    "qué ver",
    "que ver",
    "qué hacer",
    "que hacer",
    "dónde alojarse",
    "donde alojarse",
    "dónde comer",
    "donde comer",
    "qué visitar desde pamplona-iruña",
    "que visitar desde pamplona-iruna",
    "lugares",
    "espacios culturales",
    "restaurantes del reyno",
    "albergues",
    "individual",
    "grupos",
    "ver más",
    "ver mas",
    "page",
}

NAME_STOP_SUFFIXES = {
    "construido",
    "construida",
    "conocido",
    "conocida",
    "ubicado",
    "ubicada",
    "situado",
    "situada",
    "considerado",
    "considerada",
    "si",
    "en",
    "el",
    "la",
}

EXPECTED_FIELDS = {
    "Hotel": ["name"],
    "Hostel": ["name"],
    "Restaurant": ["name"],
    "Museum": ["name"],
    "Cathedral": ["name"],
    "Church": ["name"],
    "Monastery": ["name"],
    "Palace": ["name"],
    "TownHall": ["name"],
    "Park": ["name"],
    "Garden": ["name"],
    "Bridge": ["name"],
    "Market": ["name"],
    "Theatre": ["name"],
    "Arena": ["name"],
    "SportsVenue": ["name"],
    "Fortification": ["name"],
    "Gate": ["name"],
    "Dish": ["name"],
    "Dessert": ["name"],
    "Drink": ["name"],
    "FoodProduct": ["name"],
    "Event": ["name"],
    "Excursion": ["name"],
    "Activity": ["name"],
    "GuidedTour": ["name"],
    "TourismService": ["name"],
}

FAMILY_KEYWORDS = {
    "food_drink": [
        "postre", "dessert", "queso", "cheese", "licor", "sidra", "drink",
        "patxaran", "bacalao", "goxua", "pantxineta", "cuajada", "ajoarriero",
        "fritos", "menestra", "pochas",
    ],
    "event": [
        "festival", "evento", "event", "vinofest", "concierto", "gira",
        "exposición", "exposicion",
    ],
    "route_experience": [
        "ruta", "route", "excursión", "excursion", "senderismo", "cicloturismo",
        "visita guiada", "guided tour", "camino", "tour",
    ],
    "organization_service": [
        "bureau", "incoming", "guías", "guias", "profesional", "service",
        "servicio", "convention bureau", "tourism service",
    ],
    "place": [
        "parque", "park", "jardines", "garden", "puente", "bridge",
        "frontón", "fronton", "palacio", "palace", "portal", "murallas",
        "mercado", "market", "arena", "teatro", "theatre", "iglesia",
        "church", "monasterio", "cathedral", "catedral", "basilica",
        "basílica", "plaza", "ayuntamiento", "museo", "museum",
        "castillo", "alcázar", "alcazar",
    ],
    "content_page": [
        "blog", "categorías", "categorias", "todos los lugares", "planifica tu viaje",
    ],
}